[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"  # Consider restricting this if needed

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"  # More modern MIME type

[[headers]]
  for = "/assets/*.js"
    [headers.values]
    Content-Type = "application/javascript"  # More modern MIME type

[build]
  command = "npm run build"
  publish = "dist"
